### ISSUE TITLE
Refactor agent, AMM state dictionaries to classes

### ISSUE THREAD

**Issue by poliwop** [galacticcouncil/HydraDX-simulations#66]
The agent state and AMM states are currently dictionaries, they should be refactored to classes. The classes can be essentially custom types with constructors but no other methods (though perhaps these should be added later). A second possible exception to this may be a clone() or copy() method that returns a copy of an object... though perhaps existing copy module in Python handles this sufficiently.

**Comment by jepidoptera** [comment]
State dictionary is done. Probably still be worth refactoring the agents, which are currently represented as a dictionary of dictionaries of dictionaries. But that may go in the icebox for now.
